name: 'Deployment'
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  staging:
    if: github.ref_name == 'develop'
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Deploying to staging done"
  production:
    name: Deploy prod
    runs-on: ubuntu-latest
    needs: [ staging ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Deploying to prod done"
