name: 'Deployment'
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  build:
    if: ${{ github.ref_name == 'master' || github.ref_name == 'develop' }}
    name: Deploy Build
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Build image"
  staging:
    if: github.ref_name == 'develop'
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Deploying to staging done"
  preview:
    if: github.ref_name == 'master'
    name: Deploy preview
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Deploying to preview done"
  production:
    if: github.ref_name == 'master'
    name: Deploy prod
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check review status
        shell: bash
        run: |
          echo "Deploying to prod done"
