name: Create Jira ticket for Dependabot alerts
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - feat/jira-workflow

jobs:
  call-dependabot-alert-workflow:
    uses: ./.github/workflows/create-jira-issue.yml
    with:
      jira_project: ${{ vars.JIRA_PROJECT}}
      jira_parent_key: ${{ vars.JIRA_PARENT_KEY}}
      assignee_id: ${{ vars.JIRA_ASSIGNEE_ID}}
    secrets:
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      DEPENDABOT_GH_PAT: ${{ secrets.DEPENDABOT_GH_TOKEN }}
